### PR TITLE
NowFloats Retail & IGM Logs Updated

### PR DESCRIPTION
**Pull request by ajaykpandit**

### CODE REVIEW

**Comment by bluecypher** [comment]
Please submit both the utility report as well.

**Review by bluecypher — CHANGES_REQUESTED** [review]
Please submit both the utility reports for Retail logs as well and remove the referece-implementations submodule

**Comment by ajaykpandit** [comment]
> Please submit both the utility reports for Retail logs as well and remove the reference-implementations submodule

@bluecypher Changes have been done. Attached log_report for each flow. There are some issues in the log received from the buyer app itself which we can't fix.  we fixed all issues in on_<APIs>

**Comment by bluecypher** [comment]
Please rectify all the issues identified by the utility first

**Comment by bluecypher** [comment]
PR is subject to above-mentioned changes.

**Pull request closed without merging**
