### PR TITLE
Retail logs for v1.1.0

### PR DESCRIPTION
**Pull request by harshpwctech**

### CODE REVIEW

**Comment by harshpwctech** [comment]
@bluecypher, @BLR-0118,

We are a retail Buyer App as well as TSP for ISP.

Please review the logs of Euphoria Bakers (ISP) in the folder

Also the logs in the folder 27-06-2023 is for the test store created by us as a TSP.

**Comment by harshpwctech** [comment]
@bluecypher, @BLR-0118 

Please review the logs of Shathabdhi Organics (ISP) in the folder, flow 5 will not be applicable for this seller as the seller doesn't support out of stock because of not maintaining a real time inventory rather auto accepting orders for the set quantity.

**Comment by bluecypher** [comment]
@harshpwctech,
- It is necessary to test the logs with a different counterparty NP.

- Flow 2/4/5 are not accurate. They should not be divided into parts. Instead, each flow represents a single transaction on its own.

- All the flows are required for tech clearance, including Flow 5.

**Comment by bluecypher** [comment]
Please create a new PR that incorporates the aforementioned compliance requirements.

@harshpwctech

**Pull request closed without merging**
